refactor: dynamic cmdb plugin detection
hamlet-io/executor-bash pull request #218
Opened 2021-05-20 05:42 UTC by ml019

## Intent of Change
- Refactor (non-breaking change which improves the structure or operation of the implementation)

## Description
Make the token used to detect use of the cmdb plugin more specific so directory names containing `cmdb` don't result in a false positive.

## Motivation and Context
No surprises - don't trigger the dynamic cmdb behaviour unless it is really required.

## How Has This Been Tested?
Local template generation

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2021-05-23 22:26 UTC, ken9ross requested changes
Given https://github.com/hamlet-io/hamlet-bootstrap/blob/master/config.json#L48 it may be better to use 
`if contains "${GENERATION_PLUGIN_DIRS};" "cmdb;" or contains "${GENERATION_PLUGIN_DIRS};" "cmdb/;"; then`

(Not sure about syntax - essentially testing for trailing cmdb or cmdb/ contained within GENERATION_PLUGIN_DIRS when split on semi-colons. A RegExp search may be better still)

2021-05-23 23:02 UTC, ml019 commented
@ken9ross the code is checking the environment variable contents, which in the case of the bootstrap intentionally doesn't contain `cmdb` at all. 

Note sure how line 48 is relevant?

2021-05-23 23:12 UTC, ken9ross commented
L48 puts engine-plugin-cmdb.git into ${HAMLET_CLONE_ROOT}/engine/plugins/cmdb and that's the value that goes into the GENERATION_PLUGIN_DIRS envvar, so testing for "engine-plugin-cmdb" will not match if the CMDB plugin is added by bootstrap.

Am I missing something?

2021-05-24 22:53 UTC, ml019 commented
@ken9ross I think this is more what you had in mind?

2021-05-24 23:47 UTC, ml019 commented
@ken9ross should be good to merge now?

2021-05-24 23:47 UTC, ken9ross approved these changes

2021-05-24 23:47 UTC, merged